name: "Check"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - name: Check flake evaluates
        run: nix flake check --no-build
      - name: Build NixOS configuration
        run: nix build .#nixosConfigurations.frostbit.config.system.build.toplevel