name: "Check Nix Flake"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      # with:
      #   github_access_token: ${{ secrets.GITHUB_TOKEN }}
    # - run: nix build
    - run: nix flake check